spring:
  profiles:
    active: "@profiles.active@"
  hikari:
    minimum-idle: 5
    idle-timeout: 180000
    maximum-pool-size: 10
    auto-commit: true
    pool-name: MyHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: cn.zczj.hq.pojo.po
  global-config:
    dbConfig:
      capital-mode: false
      column-format: "\"%s\""
      id-type: auto #id????????id??
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??
    map-underscore-to-camel-case: true
  logging:
    level:
      cn.zczj.hq.mapper: debug
server:
  port: 8080